### ISSUE TITLE
Layout gaat niet helemaal goed in Firefox

### ISSUE THREAD

**Issue by vasilisvg** [tijsluitse/css-to-the-rescue#1]
De content is onzichtbaar in Fx 44.0 op een Mac

**Comment by vasilisvg** [comment]
Is nog steeds kapot. Kan je je issues fixen en sluiten?

**Comment by tijsluitse** [comment]
O ik dacht dat ik dit gefixed had. Ik ga het opnieuw doen!

**Comment by tijsluitse** [comment]
Done
