### ISSUE TITLE
Vreemd gedrag

### ISSUE THREAD

**Issue by vasilisvg** [tijsluitse/css-to-the-rescue#7]
# profile-picture is gewoon zichtbaar, maar wordt een overlay als je er naar linkt. Dat is op z'n zachtst gezegd verwarrend.

Saaie de-emphasize ook. Probeer blur eens.

**Comment by tijsluitse** [comment]
O ik dacht dat dat de bedoeling was. Hij moet dus eerst niet zichtbaar zijn en daarna wel?

**Comment by tijsluitse** [comment]
Done!
