### ISSUE TITLE
Min content

### ISSUE THREAD

**Issue by vasilisvg** [tijsluitse/css-to-the-rescue#9]
Kan je uitleggen wat dit precies doet? En wat er gebeurt als je het weglaat?
https://github.com/tijsluitse/css-to-the-rescue/blob/master/week-2/exercise/styles/style.css#L300

**Comment by tijsluitse** [comment]
Volgens mij heb ik dit nog niet helemaal goed gedaan. Ik ga er naar kijken!

**Comment by tijsluitse** [comment]
Het is de bedoeling dat je de holder een breedte geeft en dat de afbeelding die daarin zit altijd daarin past met de juiste afmetingen (max-content).

**Comment by tijsluitse** [comment]
Done!
